### ISSUE TITLE
for react-native >= 0.25.1, need to update import statements

### ISSUE THREAD

**Issue by ravelab** [rusel1989/react-native-flip-view#1]
to something like

import React, { Component } from 'react'
import { requireNativeComponent } from 'react-native'

in FlipClockView.js and DateCounterView.js

**Comment by rusel1989** [comment]
Hey, this is fixed [here](https://github.com/rusel1989/react-native-flip-clock/commit/49638d1cc1666203a994b351e86c94383fc6cd9b), information in readme has also been updated.
