### ISSUE TITLE
unable to update with setState

### ISSUE THREAD

**Issue by ravelab** [rusel1989/react-native-flip-view#2]
```
<DateCounterView
              dayDigitCount={2}
              date={this.state.airDate}
              mode='countdown'
              bundleName='JDFlipNumberViewIOS6' />
```

I'm able to set the count-down date only once in constructor, if I tried setting it with setState, DateCounterView counter doesn't not change, any idea?  thanks

**Comment by rusel1989** [comment]
Hey, yep that is expected behavior as this lib is now. The date prop is set only once in native code, during layoutSubviews so state change probably won't affect it. I currently don't have time to add functionality you want, but PRs are welcome :-).
